# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Custom Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          # 是否启用 hugo extend
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: burnett01/rsync-deployments@5.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          switches: -avzr --delete
          path: ./public
          remote_path: /home/ubuntu/nginx/html # 需要先手动在远程主机创建该目录，否则会执行失败
          remote_host: ${{ secrets.SERVER_IP }} # 远程主机 IP
          remote_port: ${{ secrets.SERVER_PORT }} # ssh 端口，默认为 22
          remote_user: ${{ secrets.SERVER_USER }} # ssh user
          remote_key: ${{ secrets.SERVER_KEY }} # ssh 私钥